/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tic.tac.toe;

/**
 *
 * @author lucia
 */
public class panel extends javax.swing.JFrame {

    /**
     * Creates new form panel
     */
    public panel() {
        initComponents();
        setLocationRelativeTo(null);
    }
        String texto="X";
        String texto2="O";
        String texto3= " ";
        int vista=0;
        int[][] tabla = {{0,0,0},{0,0,0},{0,0,0}};
        int inicio = (int) (Math.random()*10);       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        a1 = new javax.swing.JButton();
        a2 = new javax.swing.JButton();
        a3 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        c3 = new javax.swing.JButton();
        c2 = new javax.swing.JButton();
        c1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        g = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        a1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a1ActionPerformed(evt);
            }
        });

        a2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a2ActionPerformed(evt);
            }
        });

        a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a3ActionPerformed(evt);
            }
        });

        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3ActionPerformed(evt);
            }
        });

        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });

        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton1.setText("Inicio");
        jButton1.setActionCommand("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(c3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(a1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(a2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(a3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(g, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(a3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(a1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(a2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(c3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(g, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    private void a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a3ActionPerformed
        if(!a3.isSelected())
        {
            a3.setText(texto);
            tabla[0][2]=1;
            respuesta(3);
        }
    }//GEN-LAST:event_a3ActionPerformed

    private void a1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a1ActionPerformed
        if(!a1.isSelected()){
           a1.setText(texto);
           tabla[0][0]=1;  
           respuesta(1);
        }
    }//GEN-LAST:event_a1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    switch(inicio){
        case 5:
             System.out.println(51);
            break;
        case 6:
            System.out.println(51);
            break;
        case 7:
            System.out.println(51);
            break;
        case 8:
            System.out.println(51);
            break;
        case 9:
            System.out.println(51);
            break;
    }
            a1.setText(texto3); 
            a2.setText(texto3); 
            a3.setText(texto3); 
            b1.setText(texto3); 
            b2.setText(texto3); 
            b3.setText(texto3); 
            c1.setText(texto3); 
            c2.setText(texto3); 
            c3.setText(texto3);
            a1.setEnabled(true);
            a2.setEnabled(true);
            a3.setEnabled(true);
            b1.setEnabled(true);
            b2.setEnabled(true);
            b3.setEnabled(true);
            c1.setEnabled(true);
            c2.setEnabled(true);
            c3.setEnabled(true);
            vista=0;
            for (int i = 0; i < 3; i++) {
            tabla[i][0] = 0;
            }
            for (int j = 0; j < 3; j++) {
            tabla[j][1] = 0;
            }
            for (int k = 0; k < 3; k++) {
            tabla[k][2] = 0;
            }   
            g.setText(texto3);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void a2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a2ActionPerformed
        if(!a2.isSelected()){
           a2.setText(texto);
           tabla[0][1]=1;
           System.out.println(tabla[0][1]);
           respuesta(2);
        }
    }//GEN-LAST:event_a2ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
         if(!b1.isSelected()){
           b1.setText(texto);
           tabla[1][0]=1;
           respuesta(4);
        }
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
         if(!b2.isSelected()){
           b2.setText(texto);
           tabla[1][1]=1;
           respuesta(5);
        }
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
         if(!b3.isSelected()){
           b3.setText(texto);
           tabla[1][2]=1;
           respuesta(6);
        }
    }//GEN-LAST:event_b3ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
         if(!c1.isSelected()){
           c1.setText(texto);
           tabla[2][0]=1;
           respuesta(7);
        }
    }//GEN-LAST:event_c1ActionPerformed

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
        if(!c2.isSelected()){
           c2.setText(texto);
           tabla[2][1]=1;
           respuesta(8);
        }
    }//GEN-LAST:event_c2ActionPerformed

    private void c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3ActionPerformed
        if(!c3.isSelected()){
           c3.setText(texto);
           tabla[2][2]=1;
           respuesta(9);
        }
    }//GEN-LAST:event_c3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panel().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton a1;
    public javax.swing.JButton a2;
    public javax.swing.JButton a3;
    public javax.swing.JButton b1;
    public javax.swing.JButton b2;
    public javax.swing.JButton b3;
    public javax.swing.JButton c1;
    public javax.swing.JButton c2;
    public javax.swing.JButton c3;
    public static javax.swing.JLabel g;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
  
    private void respuesta(int a) {
        //recorrido por fila  
        switch(a){
            case 1:
                if(tabla[0][2]==1){
                   if(tabla[0][1]==0){
                   a2.setText(texto2);
                   a2.setEnabled(false);
                   tabla[0][1]=2;
                    break;
               }
               }
                if(tabla[2][2]==1){
                   if(tabla[1][1]==0){
                   b2.setText(texto2);
                   b2.setEnabled(false);
                   tabla[1][1]=2;
                    break;
               }
               }
               if(tabla[1][1]==1){
                   if(tabla[2][2]==0){
                   c3.setText(texto2);
                   c3.setEnabled(false);
                   tabla[2][2]=2;
                    break;
               }
               }
              
               if(tabla[0][1]==0){
                   a2.setText(texto2);
                   a2.setEnabled(false);
                   tabla[0][1]=2;
                    break;
               }
               if(tabla[1][0]==0){
                   b1.setText(texto2);
                   b1.setEnabled(false);
                   tabla[1][0]=2;
                    break;
               }
               
               if(tabla[1][1]==0){
                   b2.setText(texto2);
                   b2.setEnabled(false);
                   tabla[1][1]=2;
                    break;   
               }            
                break;
            case 2:
                if(tabla[2][1]==1){
                   if(tabla[1][1]==0){
                   b2.setText(texto2);
                   b2.setEnabled(false);
                   tabla[1][1]=2;
                    break;
               }
               }
                if(tabla[1][1]==1){
                   if(tabla[2][1]==0){
                   c2.setText(texto2);
                   c2.setEnabled(false);
                   tabla[1][1]=2;
                    break;
               }
               }
                if(tabla[0][0]==0){
                   a1.setText(texto2);
                   a1.setEnabled(false);
                   tabla[0][0]=2;
                    break;
               }
               if(tabla[0][2]==0){
                   a3.setText(texto2);
                   a3.setEnabled(false);
                   tabla[0][2]=2;
                    break;
               }
               if(tabla[1][0]==0){
                   b1.setText(texto2);
                   b1.setEnabled(false);
                   tabla[1][0]=2;
                    break;
               }
               if(tabla[1][1]==0){
                   b2.setText(texto2);
                   b2.setEnabled(false);
                   tabla[1][1]=2;
                    break;
               }
               if(tabla[1][2]==0){
                   b3.setText(texto2);
                   b3.setEnabled(false);
                   tabla[1][2]=2;
                    break;
               }
                break;
                
            case 3:
                
                 if(tabla[2][2]==1){
                   if(tabla[1][2]==0){
                   b3.setText(texto2);
                   b3.setEnabled(false);
                   tabla[1][1]=2;
                    break;
               }
               }
                 if(tabla[2][0]==1){
                   if(tabla[1][1]==0){
                   b2.setText(texto2);
                   b2.setEnabled(false);
                   tabla[1][1]=2;
                    break;
               }
               }
                
                 if(tabla[0][1]==0){
                   a2.setText(texto2);
                   a2.setEnabled(false);
                   tabla[0][1]=2;
                    break;
               }
               if(tabla[1][1]==0){
                   b2.setText(texto2);
                   b2.setEnabled(false);
                   tabla[1][1]=2;
                    break;
               }
               if(tabla[1][2]==0){
                   b3.setText(texto2);
                   b3.setEnabled(false);
                   tabla[1][2]=2;
                    break;
               }
               
                break;
            case 4:
                if(tabla[1][2]==1){
                   if(tabla[1][1]==0){
                   b2.setText(texto2);
                   b2.setEnabled(false);
                   tabla[1][1]=2;
                    break;
               }
               }
                if(tabla[1][1]==1){
                   if(tabla[1][2]==0){
                   b3.setText(texto2);
                   b3.setEnabled(false);
                   tabla[1][2]=2;
                    break;
               }
               }
                if(tabla[0][0]==1){
                   if(tabla[2][0]==0){
                   c1.setText(texto2);
                   c1.setEnabled(false);
                   tabla[2][0]=2;
                    break;
               }
               }
                 if(tabla[0][0]==0){
                   a1.setText(texto2);
                   a1.setEnabled(false);
                   tabla[0][0]=2;
                    break;
               }
               if(tabla[1][1]==0){
                   b2.setText(texto2);
                   b2.setEnabled(false);
                   tabla[1][1]=2;
                    break;
               }
               if(tabla[2][0]==0){
                   c1.setText(texto2);
                   c1.setEnabled(false);
                   tabla[2][0]=2;
                    break;
               }
               if(tabla[2][1]==0){
                   c2.setText(texto2);
                   c2.setEnabled(false);
                   tabla[2][1]=2;
                    break;
               }
               
                break;
            case 5:
                
                if(tabla[2][0]==1){
                   if(tabla[0][2]==0){
                   a3.setText(texto2);
                   a3.setEnabled(false);
                   tabla[0][2]=2;
                    break;
               }
               }   
                 if(tabla[0][0]==1){
                   if(tabla[2][2]==0){
                   c3.setText(texto2);
                   c3.setEnabled(false);
                   tabla[2][2]=2;
                    break;
               }
               }
                  if(tabla[0][2]==1){
                   if(tabla[2][0]==0){
                   c1.setText(texto2);
                   c1.setEnabled(false);
                   tabla[2][0]=2;
                    break;
               }
               }
                if(tabla[1][0]==1){
                   if(tabla[1][2]==0){
                   b3.setText(texto2);
                   b3.setEnabled(false);
                   tabla[1][2]=2;
                    break;
               }
               }
                
                if(tabla[0][1]==1){
                   if(tabla[2][1]==0){
                   c2.setText(texto2);
                   c2.setEnabled(false);
                   tabla[2][1]=2;
                    break;
               }
               }
               if(tabla[2][1]==1){
                   if(tabla[0][1]==0){
                   a2.setText(texto2);
                   a2.setEnabled(false);
                   tabla[0][1]=2;
                    break;
               }
               }
              
               if(tabla[0][2]==0){
                   a3.setText(texto2);
                   a3.setEnabled(false);
                   tabla[0][2]=2;
                    break;
               }
               if(tabla[1][0]==0){
                   b1.setText(texto2);
                   b1.setEnabled(false);
                   tabla[1][0]=2;
                    break;
               }
               if(tabla[1][2]==0){
                   b3.setText(texto2);
                   b3.setEnabled(false);
                   tabla[1][2]=2;
                    break;
               }
               if(tabla[2][0]==0){
                   c1.setText(texto2);
                   c1.setEnabled(false);
                   tabla[2][0]=2;
                    break;
               }
               if(tabla[2][1]==0){
                   c2.setText(texto2);
                   c2.setEnabled(false);
                   tabla[2][1]=2;
                    break;
               }
               if(tabla[2][2]==0){
                   c3.setText(texto2);
                   c3.setEnabled(false);
                   tabla[2][2]=2;
                    break;
               }
                break;
            case 6:
                
                 if(tabla[1][1]==1){
                   if(tabla[1][0]==0){
                   b1.setText(texto2);
                   b1.setEnabled(false);
                   tabla[1][0]=2;
                    break;
               }
               }
                 if(tabla[1][0]==1){
                   if(tabla[1][1]==0){
                   b2.setText(texto2);
                   b2.setEnabled(false);
                   tabla[1][1]=2;
                    break;
               }
               }
                 if(tabla[0][2]==0){
                   a3.setText(texto2);
                   a3.setEnabled(false);
                   tabla[0][2]=2;
                    break;
               }
               if(tabla[1][1]==0){
                   b2.setText(texto2);
                   b2.setEnabled(false);
                   tabla[1][1]=2;
                    break;
               }
               if(tabla[0][1]==0){
                   a2.setText(texto2);
                   a2.setEnabled(false);
                   tabla[0][1]=2;
                    break;
               }
               if(tabla[2][1]==0){
                   c2.setText(texto2);
                   c3.setEnabled(false);
                   tabla[2][1]=2;
                    break;
               }
               if(tabla[2][2]==0){
                   c3.setText(texto2);
                   c3.setEnabled(false);
                   tabla[2][2]=2;
                    break;
               }
               
                break;
            case 7:
                
                 if(tabla[1][1]==1){
                   if(tabla[0][2]==0){
                   a3.setText(texto2);
                   a3.setEnabled(false);
                   tabla[0][2]=2;
                    break;
               }
               }
                  if(tabla[0][2]==1){
                   if(tabla[1][1]==0){
                   b2.setText(texto2);
                   b2.setEnabled(false);
                   tabla[1][1]=2;
                    break;
               }
               }
                if(tabla[0][2]==1){
                   if(tabla[1][2]==0){
                   b3.setText(texto2);
                   b3.setEnabled(false);
                   tabla[1][2]=2;
                    break;
               }
               }
                 
                if(tabla[1][0]==0){
                   b1.setText(texto2);
                   b1.setEnabled(false);
                   tabla[1][0]=2;
                    break;
               }
                if(tabla[1][1]==0){
                   b2.setText(texto2);
                   b2.setEnabled(false);
                   tabla[1][1]=2;
                    break;
               }
                if(tabla[2][1]==0){
                   c2.setText(texto2);
                   c2.setEnabled(false);
                   tabla[2][1]=2;
                    break;
               }
                break;
            case 8:
                
                if(tabla[1][1]==1){
                   if(tabla[0][1]==0){
                   a2.setText(texto2);
                   a2.setEnabled(false);
                   tabla[0][1]=2;
                    break;
               }
               }
                
                if(tabla[0][1]==1){
                   if(tabla[1][1]==0){
                   b2.setText(texto2);
                   b2.setEnabled(false);
                   tabla[1][1]=2;
                    break;
               }
               }
                if(tabla[2][1]==1){
                   if(tabla[2][2]==0){
                   c3.setText(texto2);
                   c3.setEnabled(false);
                   tabla[2][2]=2;
                    break;
               }
               }
                
                if(tabla[2][0]==0){
                   c1.setText(texto2);
                   c1.setEnabled(false);
                   tabla[2][0]=2;
                    break;
               }
                if(tabla[1][0]==0){
                   b1.setText(texto2);
                   b1.setEnabled(false);
                   tabla[1][0]=2;
                    break;
               }
                if(tabla[1][1]==0){
                   b2.setText(texto2);
                   b2.setEnabled(false);
                   tabla[1][1]=2;
                    break;
               }
                if(tabla[1][2]==0){
                   b3.setText(texto2);
                   b3.setEnabled(false);
                   tabla[1][2]=2;
                    break;
               }
                if(tabla[2][2]==0){
                   c3.setText(texto2);
                   c3.setEnabled(false);
                   tabla[2][2]=2;
                    break;
               }
                break;
            case 9:
                 if(tabla[0][2]==1){
                   if(tabla[1][2]==0){
                   b3.setText(texto2);
                   b3.setEnabled(false);
                   tabla[1][2]=2;
                    break;
               }
               }
                 
                if(tabla[0][0]==1){
                   if(tabla[1][1]==0){
                   b2.setText(texto2);
                   b2.setEnabled(false);
                   tabla[1][1]=2;
                    break;
               }
               }
                
                if(tabla[2][1]==0){
                   c2.setText(texto2);
                   c2.setEnabled(false);
                   tabla[2][1]=2;
                    break;
               }
                if(tabla[1][2]==0){
                   b3.setText(texto2);
                   b3.setEnabled(false);
                   tabla[1][2]=2;
                    break;
               }
                if(tabla[1][1]==0){
                   b2.setText(texto2);
                   b2.setEnabled(false);
                   tabla[1][1]=2;
                    break;
               }
                break;
        }    
        ganadorjugador();
        
    }
    private void ganadorjugador(){
        int h=0,ha=0,hb=0,hc=0,hd=0;
        int m=0;
        
        for(int i=0;i<3;i++){
            if(tabla[0][i]==1){
                h=h+1;
                hg(h);
            };
        }
        
        for(int i=0;i<3;i++){
            if(tabla[1][i]==1){
                ha=ha+1;
                hg(ha);
            }}
         
        for(int i=0;i<3;i++){
            if(tabla[2][i]==1){
                hb=hb+1;
                hg(hb);
            }}
        
         for(int i=0;i<3;i++){
            if(tabla[i][i]==1){
                hc=hc+1;
                hg(hc);
            }}
         for(int i=0;i<3;i++){
            if(tabla[0][i]==1){
                hd=hd+1;
                hg(hd);
            }}
        }
    private void hg(int hm){

    if(hm==3)
    {
        g.setText("Gana el jugador");
    }
    }
}